MONGODB_HOST : mongodb-{{ env }}.dawsdevops86.fun #mongodb-dev.dawsdevops86.fun
REDIS_HOST   : redis-{{ env }}.dawsdevops86.fun
CATALOGUE_HOST : catalogue-{{ env }}.dawsdevops86.fun
CART_HOST : cart-{{ env }}.dawsdevops86.fun
MYSQL_HOST : mysql-{{ env }}.dawsdevops86.fun
USER_HOST : user-{{ env }}.dawsdevops86.fun
RABBITMQ_HOST : rabbitmq-{{ env }}.dawsdevops86.fun
SHIPPING_HOST : shipping-{{ env }}.dawsdevops86.fun
PAYMENT_HOST : payment-{{ env }}.dawsdevops86.fun