- name: create ec2 and r53
  hosts: localhost
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0a1b4bbcf0ceb6b58
    zone_id: Z0362302V4UECAHA23E4
    domain_name: dawsdevops86.fun
    # we can pass instances through command line using -e
    # instances:
    # - mongodb
    # - redis
    # - mysql
    # - rabbitmq
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output


  # - name: print the ec2_output  ==> to much text that's why we comment
  #   ansible.builtin.debug:
  #    msg: "{{ ec2_output }}"

  # - name: print public_ip
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].public_ip_address }}"  ====> I got formate comment off 
  #   loop: "{{ ec2_output.results }}" 


  # - name: print private_ip
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].private_ip_address }}"  ====> I got formate comment off
  #   loop: "{{ ec2_output.results }}"



  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.dawsdevops86.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"